name: Duolingo XP Gainer

on:
  # Schedule to run at specific times (using cron)
  schedule:
    - cron: '0 21 * * *'  # 4:00 AM WIB
    - cron: '0 5 * * *'   # 12:00 PM WIB
    - cron: '0 11 * * *'  # 6:00 PM WIB
    - cron: '0 14 * * *'  # 9:00 PM WIB
    - cron: '5 3 * * *'   # 10:05 AM WIB

  # Allow manual triggering
  workflow_dispatch:
    inputs:
      lessons:
        description: 'Number of lessons to complete'
        required: true
        default: 5

jobs:
  doing-lesson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Run the Python script with secrets and lessons input
      - name: Run Duolingo XP Gainer
        run: python -u duo.py ${{ github.event.inputs.lessons }}
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
