name: Duolingo Streak Keeper

on:
  # Schedule to run at specific times (using cron)
  schedule:
    - cron: '0 */6 * * *'  # run every 6 hours every day

jobs:
  doing-lesson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Run the Python script with secrets and lessons input
      - name: Run Duolingo XP Gainer
        run: python -u duo.py 50
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
